[package]
name = "walrus_forms"
edition = "2024.beta"
license = "MIT"
authors = ["Walrus Forms Team"]

[dependencies]
sui_groups = { local = "./sui_groups" }

[addresses]
walrus_forms = "0x0"
sui_groups = "0x541840ae7df705d1c6329c22415ed61f9140a18b79b13c1c9dc7415b115c1ba8"
